### PR TITLE
Adds SuperLearner wrapper functionality, minor changes from use in ACIC

### PR DESCRIPTION
**Pull request by nhejazi**
The commits contained in this pull request represent a number of changes that were made to the core functionality of HAL as part of an effort to prepare the function for use in a `SuperLearner` meant for implementation in [ACIC 2017](http://causal.unc.edu/acic2017/). Some of these include:

* Adding new parameters to `hal` that allow for automatic variable filtering when the dimensionality of the input data matrix is high, but resources are constrained. __(implemented in `hal_new.R`, to avoid conflict with `hal.R`)__
* Addition of screeners, within `hal`, that allow for variable reduction, prior to any analysis -- again, a time-saving effort to ease use by non-experts. __(implemented in `hal_new.R`, to avoid conflict with `hal.R`)__
* Addition of simulation scripts used in testing the algorithm for [ACIC 2017](http://causal.unc.edu/acic2017/).
* Re-organization of the repository such that files not associated with the R package are moved to the new `sandbox` directory, which is not included with the R package (via `.Rbuildignore`)
* Minor revisions to the `README.md` and `DESCRIPTION` files, to add new authors, badges, edit syntax for style consistency with GitHub-flavored Markdown, etc.
* Addition of a user-facing support website via [`pkgdown`]() -- this website is currently hosted at [nimahejazi/halplus](http://nimahejazi.org/halplus/), but should eventually be moved to [benkeser.github.io/halplus](https://benkeser.github.io/halplus/).

**IMPORTANT:** this pull request contains a large number of commits, many of them created by necessity to merge changes in the fork with developments in the main repo. Assuming that this pull request will be merged, __please use the [squash and merge](https://github.com/blog/2141-squash-your-commits) feature__, as this will generate a much clearer revision history for this project moving forward.

__ADDITIONAL NOTE:__ while the summary number of files changes (specifically, 43) is rather large, _many of the changes are superficial:_ __29/43__ files changed come from renaming/moving and the adding of the static `pkgdown` site -- this rises to __35/43__ if you include the likes of `.Rbuildignore`, `.gitignore`, `LICENSE`, `DESCRIPTION`, `halplus.Rproj`, `README.md`. _This means any reviewers ought to only concern themselves with changes to **8/43** files_, a rather small number.

### CODE REVIEW

**Comment by ck37** [comment]
Hi Nima,

Great to see the work on this project. However I don't think it is a good use of github or git to send over a PR with 41 commits in it across a wide number of items. It's not feasible for anyone to review or comment on all of these omnibus changes, and it doesn't allow someone to pick and choose which items to merge.

In my opinion, and I don't speak for David (or Oleg), this needs to be broken up into separate PRs as is standard for github projects. Each bullet point can roughly be a PR that is reasonably reviewable. Then David can one-click merge PRs that look good or discuss ones that need discussion.

More github etiquette - instead of including the variety of merger items, it is appropriate to rebase to upstream/master before submitting PRs except when a few simple extra commits are included - that should eliminate the merge commits. Instead of asking David to squash commits, the PR submitter should do so in those separate PRs.

Extra links:
- https://readwrite.com/2014/07/02/github-pull-request-etiquette/
- https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

A few more substantive items:

1. Not sure I follow why a p-value screener is added to hal_new.R when it can already be done directly in SuperLearner in a more general way. We discussed this some at ACIC meetings I think.
2. The screener assumes an A variable, which is not good: https://github.com/nhejazi/halplus/blob/master/R/hal_new.R#L80
3. There don't seem to be any tests for hal_new.R, which probably would have surfaced issue 2.
4. As I've mentioned, I don't support manually generated pkgdown sites as their utility is even more minimal if they're out of date. An automated version would be reasonable.

Again, with 41 commits and 43 files changed there are probably other things to discuss. Also happy to chat more at the Monday meeting, etc.

Thanks,
Chris

**Comment by nhejazi** [comment]
Hi Chris ---

Thanks for the substantial feedback. Re git/GitHub etiquette: In general, I am aware of the problem with pull requests as large as this one, and of each of the techniques you've brought up. I agree with most of what you've brought up, but only as far as it extends to large open source projects (consider, [matplotlib](https://github.com/matplotlib/matplotlib) w/ nearly _22,000 commits_, for example), and/or when the PR is from someone that is not already a collaborator on the project. Unfortunately, this PR was the work of little time, largely because it would be a poor use of my -- and anyone else's -- time to be curating a project history for software that is in its infancy. I asked David to squash the commits because that is the fastest way to re-obtain a clean working history (We can speak more on this offline if necessary.)

I've tried to respond to a few of your more substantive concerns below, using your original numbering for reference:

1. We did indeed discuss the fact that screening can be done within SL when using HAL at at least one of our ACIC meetings. My position remains just as it did then -- specifically, that it is important for HAL to be a functional algorithm outside of Super Learner. Nobody would seriously write an ML algorithm for use only with a very specific ensemble learner, so it doesn't quite make sense to leave screening procedures out of HAL altogether. (I would imagine there are cases where someone might want to try out HAL outside of the SL framework.) I've spoken with David about this idea, and, unless I recall incorrectly, he was on board with this -- it was partly because of this that he was the requested reviewer.

2. hal_new.R is a function in its infancy (and does not currently interfere with hal.R); it is a placeholder for further fleshing out a revised version of the algorithm that could incorporate screeners. It is not meant to be user-facing at this point -- and should, more properly, be moved to a development branch.

3. See above. Writing tests for functions that are not yet user-facing seems an odd practice... Coverage will drop slightly in the short-term, until such functions are moved to a development branch, at which point the proper/accurate level of coverage will be restored.

4. As you've pointed out, we've disagreed on this topic before. I wouldn't characterize the utility of `pkgdown` sites as generally minimal (only if severely out of date), and I use them for all R packages that I build/maintain. It's important to have documentation that is easily accessible to the user, and it is generally unreasonable to expect someone to download your R package just to explore the vignette. If and when Hadley & Co. provide facilities for auto-building `pkgdown` sites, I would of course support these over manually built versions. If you feel strongly, you could, of course, work around this (minor) annoyance via a very simple `Make` recipe -- for example:
```bash
export LC_TIME=en_US.UTF-8
MESSAGE="Re-building package documentation: $(date)"

docs:
    Rscript -e "devtools::document()"
    Rscript -e "pkgdown::build_site()"
    git add *
    git commit -m "$MESSAGE"
    git push origin master
```

**Comment by ck37** [comment]
Clear and separate PRs are helpful for any project in which people are reviewing each other's code, such as me reviewing your code for this PR. It's basic respect for collaborators' time and for the quality of the software. As long as we're using git why not do a good job of it? The omnibus PR approach brings down the quality of the targeted learning software ecosystem, which certainly doesn't need any additional help. Kudos to matplotlib on the *22,000 commits*, but Eric and I do this on SuperLearner without incident and a bold *324 commits*. I don't see the benefit to postponing good PRs to an unknown future date.

1. Fair point on including one built-in screener given that Hal is so computationally intensive. As an aside, I suspect that the majority of people using Hal would use an ML framework, which is what targeted learning theory would advise generally. Beyond SuperLearner there's mlr and caret, both of which have multiple feature selection options, and need to be considered for a general supervised learning package. But yeah, might as well support randos who use only hal, provided our one screener is largely bug-free.

2. I suggest that you simply remove A from the formula, then this item will be resolved. What's the point of arguing with a minor item that points out an error - might as well just skip the review. This item could have been fixed in the time it took you to write your response...

3. Tests should be written as features are developed, not post hoc. We're not going to make progress on code quality if new features are developed without tests, esp. people who already know how to write tests. I don't see the need for a development branch if features are added with tests - a develop branch is not worth the extra overhead imo.

4. Any manual documentation build is going to lead to outdated documentation, which is exactly what documentation should not be. I don't support polluting the commit log with documentation building messages either. It's not hard to automate it and accomplishes 1) user availability, 2) automatic correctness, 3) not polluting commit log: https://github.com/ck37/ck37r/blob/master/scripts/deploy_pkgdown.sh

**Comment by nhejazi** [comment]
Again, I think we mostly agree on your points about git/GitHub etiquette. Obviously, it saves us all a fair degree of trouble to create reasonable PRs that are actually review-able. Use this as an example of what not to do in the future if you'd like, but I'll just re-state that it's a poor use of time to go through protocols of proper etiquette when the tool in question is not yet mature. Might be worth noting that in reaching for an example you used SuperLearner...which is similar enough to matplotlib for the point I was making -- that is, it is software with an existing (extensive) user base. To my knowledge, HAL does not have any committed users (even we had to exclude it from our ACIC entry), making it a much different case.

I've already said I agree, but it's also worth noting that when you post comments about particular protocols for using git/GitHub, you're touching on only one model: this makes the statement that I am being disrespectful of the reviewers' time quite (strong and) incorrect (e.g., consider [zeromq](https://github.com/zeromq/czmq), a much larger project, which has the policy of automatically merging any PR immediately -- admittedly a bit weird, but works for them...and their software is very widely used, by a community larger than we could so much as hope for).

Also worth noting that a reviewer should have quickly caught that exactly __29/43__ files changed represented _superficial_ changes (e.g., renaming files due to being moved to `sandbox`, or simply adding `pkgdown` files) -- this rises to __35/43__ if you include the likes of `.Rbuildignore`, `.gitignore`, `LICENSE`, `DESCRIPTION`, `halplus.Rproj`, `README.md` -- rather than getting caught up in the (admittedly large) summary number. I've amended my comments in the PR to add this information.

Some responses to your points, again:

1. This is just a first step for including screening methods in HAL. Ideally, it should offer several that we (as in the Targeted Learning community) approve of and have thought about. One might consider screening methods that do more than just a simple t-test... Sure, users can go outside to `mlr` or `caret` if they like -- and we should allow them to -- but _they shouldn't feel that they have to, just to get HAL to run_.

2. Fair enough, I should have caught this. That said, it's not really a PR-stopping error, given that the function itself is not user-facing.

3. I mostly agree: it's good practice to write tests for functions that are complete (and user-facing). It doesn't make sense to spend time writing tests when you're still experimenting with a new feature... Use of several branches is generally good practice -- for example [1](http://nvie.com/posts/a-successful-git-branching-model/) or [2](https://de.atlassian.com/git/tutorials/comparing-workflows). The idea of writing a test every time you write a new feature is a good one, but there has to be room for unrestricted development as well.

4. If you already have a solution you like, why not just suggest it outright? Looking at your script, it looks fine, though the trick it uses to avoid "polluting" the git history is just using a `gh-pages` branch... (I'm not sure how this reconciles with your opposition to adding complexity via multiple branches -- e.g., `develop`, `release`, etc.)

**Comment by ck37** [comment]
- I guess I need to be clearer: you are wasting my time with this PR & disappointing discussion, and in my opinion David's as well. The random policies of a random repo are irrelevant.
- Just remove the A from the formula and commit the change. No further comment is needed.
- I'm aware of multi-branch models. Maintaining several branches is not worth the hassle for a small project imo.
- Here is the story of why I didn't link my auto-doc example initially: you had already shown in the SuperLearner queue that you knew of the automated solution. I added the link due to you suggesting there was no currently available automation approach, when you know that there is. I won't waste my time in the future.
- I'm fine with an automated script deploying documentation to what is essentially a read-only branch. It's (obviously?) different than a group of maintainers pushing source code around multiple branches for no benefit.

And with that, I won't be commenting further on this PR. Congratulations on making the worst PR I've ever seen and combining that with the worst PR discussion I've ever had. The ol' 1-2.

**Comment by osofr** [comment]
Great discussion guys! First of, children, please don't fight :))) Second,
some of my random two cents on your discussion.

Tests. Should be written for any user or non-user facing functions. If the
function in question is still being flashed out and undergoing development,
then at least create test placeholders for the future, with comments on
what you want to test (because no one will remember otherwise).

Dev branches. Perhaps a savy git user can handle the workflow with several
branches, I find them absolutely horrible (no strong feelings though for
those who can make it work). It only makes sense to me to create a branch
when you quickly want to test something out, break the code, do something
totally crazy or work on a quick fix. With the idea that the branch will
get quickly merged into main and is deleted afterwards. Again, if people
can make it work, then kudos to them. My impression is that most of
branches out there are just forgotten dead corpses (including mine).

Docs. I like Nima's idea of a doc website. But the manual build is a real
issue here, I have to agree. Is there some way to automate this indeed?
What about sticking the manual into rmarkdown vignette and committing the
compiled HTML/PDF, along with source (I know Chris is gonna freak out about
this one, but I think it's totally ok). I'm not sure if the first step can
be automated though (sticking manual into vignette), plus it will look/read
pretty terribly.


Big PRs. I am with Nima here. No one is using HAL yet (sorry David, hope
you aren't too offended). We all have limited time and have to make some
compromises on proper etiquette. As long as PR clearly describes what is
being done, I don't see a problem. We have 4 people on this repo of which I
believe only Chris and Nima are current active developers. I honestly would
rather see one large PR than have 100 small ones hanging in the inbox.

On Jun 6, 2017 9:38 AM, "Nima Hejazi" <notifications@github.com> wrote:

Again, I think we mostly agree on your points about git/GitHub etiquette.
Obviously, it saves us all a fair degree of trouble to create reasonable
PRs that are actually review-able. Use this as an example of what not to do
in the future if you'd like, but I'll just re-state that it's a poor use of
time to go through protocols of proper etiquette when the tool in question
is not yet mature. Might be worth noting that in reaching for an example
you used SuperLearner...which is similar enough to matplotlib for the point
I was making -- that is, it is software with an existing (extensive) user
base. To my knowledge, HAL does not have any committed users (even we had
to exclude it from our ACIC entry), making it a much different case.

I've already said I agree, but it's also worth noting that when you post
comments about particular protocols for using git/GitHub, you're touching
on only one model: this makes the statement that I am being disrespectful
of the reviewers' time quite (strong and) incorrect (e.g., consider zeromq
<https://github.com/zeromq/czmq>, a much larger project, which has the
policy of automatically merging any PR immediately -- admittedly a bit
weird, but works for them...and their software is very widely used).

It's also worth noting that a reviewer should have quickly caught that
exactly *29/43* files changed represented *superficial* changes (e.g.,
renaming files due to being moved to sandbox, or simply adding pkgdown
files) -- *35/43* if you include the likes of .Rbuildignore, .gitignore,
LICENSE, DESCRIPTION, halplus.Rproj, README.md -- rather than getting
caught up in the (admittedly large) summary number. I've amended my
comments in the PR to add this information.

Some responses to your points, again:

   1.

   This is just a first step for including screening methods in HAL.
   Ideally, it should offer several that we (as in the Targeted Learning
   community) approve of and have thought about. One might consider screening
   methods that do more than just a simple t-test (e.g., I've implemented
   variable importance / selection techniques using tmle.npvi based on
   suggestions from MvdL). Sure, users can go outside to mlr or caret if
   they like -- and we should allow them to -- but *they shouldn't feel
   that they have to, just to get HAL to run*.
   2.

   Fair enough, I should have caught this. That said, it's not really a
   PR-stopping error, given that the function itself is not user-facing.
   3.

   I mostly agree: it's good practice to write tests for functions that are
   complete (and user-facing). It doesn't make sense to spend time writing
   tests when you're still experimenting with a new feature... Use of several
   branches is generally good practice -- for example 1
   <http://nvie.com/posts/a-successful-git-branching-model/> or 2
   <https://de.atlassian.com/git/tutorials/comparing-workflows>. The idea
   of writing a test every time you write a new feature is a good one, but
   there has to be room for unrestricted development as well.
   4.

   If you already have a solution you like, why not just suggest it
   outright? Looking at your script, it looks fine, though the trick it uses
   to avoid "polluting" the git history is just using a gh-pages branch...
   (I'm not sure how this reconciles with your opposition to adding complexity
   via multiple branches -- e.g., develop, release, etc.)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/benkeser/halplus/pull/1#issuecomment-306365305>, or mute
the thread

**Comment by benkeser** [comment]
Hi guys,

Thanks, Nima, for putting in some work on this repository -- good to see
things moving forward a bit. And thanks, Chris for making suggestions to
optimize workflow moving forward. In the future, it may be more efficient
and collegial to have these types of discussions in person. I hope we can
have a constructive dialogue for how to best move forward with this work.

I agree with the points Oleg raised. The software is indeed pretty far from
production quality, so it doesn't seem like a big deal to me if we're a bit
sloppy in workflow at this point. As we move towards an R package release,
we can be more picky about how we go about things.

Nima and Chris had both expressed interest in getting more work underway on
this project over the summer. Perhaps it would be good to set up a blue
jeans and come up with a couple concrete projects/goals for the summer.
Does that sound reasonable?

Best,
David

**Pull request closed without merging**
